version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn jobtracker.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - ./.env.db

volumes:
  postgres_data:
