version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["./entrypoint.sh"]
    command: gunicorn jobtracker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env