# Generated by Django 3.0.8 on 2020-08-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-apply_date', 'title']},
        ),
    ]
