# Generated by Django 3.0.8 on 2020-08-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20200825_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('yes', 'Yes'), ('noreply', 'No Reply'), ('rejected', 'Rejected')], default='noreply', max_length=50),
        ),
    ]
