# Generated by Django 3.0.8 on 2020-08-25 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='status',
        ),
    ]
